services:
  himas-server:
    build: .
    ports:
      - "8080:8080"
    command: python -c "from src.federated.flower_server import start_federated_server; start_federated_server()"
    
  hospital-1:
    build: .
    depends_on:
      - himas-server
    command: python hospital_client.py 0 5
    
  hospital-2:
    build: .
    depends_on:
      - himas-server  
    command: python hospital_client.py 1 10